/* ============================================================
   Builds the phone-app web bundle into  mobile/www/

   Run:  node build-mobile.js  [https://your-live-site.com]

   The address you pass is where the app fetches fresh content from,
   so your admin edits reach people who already installed the app.
   Leave it out and the app just uses the copy baked in at build time.
   ============================================================ */
const fs = require('fs');
const path = require('path');

const ROOT   = __dirname;
const PUBLIC = path.join(ROOT, 'public');
const DATA   = path.join(ROOT, 'data');
const WWW    = path.join(ROOT, 'mobile', 'www');

const API_BASE = (process.argv[2] || '').replace(/\/$/, '');

/* --- helpers --- */
function rmrf(p) { fs.rmSync(p, { recursive: true, force: true }); }
function copyDir(from, to, skip = []) {
  if (!fs.existsSync(from)) return;
  fs.mkdirSync(to, { recursive: true });
  for (const e of fs.readdirSync(from, { withFileTypes: true })) {
    if (skip.includes(e.name)) continue;
    const s = path.join(from, e.name), t = path.join(to, e.name);
    e.isDirectory() ? copyDir(s, t, skip) : fs.copyFileSync(s, t);
  }
}

/* --- build --- */
rmrf(WWW);
fs.mkdirSync(WWW, { recursive: true });

// the site, minus the things an app shouldn't ship
copyDir(PUBLIC, WWW, ['admin.html', 'sw.js']);

// bundled content so the app works with no signal
fs.copyFileSync(path.join(DATA, 'content.json'), path.join(WWW, 'content.json'));

// bundled photos, so uploaded images show offline too
copyDir(path.join(DATA, 'uploads'), path.join(WWW, 'uploads'));

// app-only settings, written as its own file…
const cfg =
  `/* generated by build-mobile.js — do not edit by hand */\n` +
  `window.__NO_SW__ = true;\n` +
  (API_BASE ? `window.__API_BASE__ = ${JSON.stringify(API_BASE)};\n`
            : `/* no live address given: the app uses its bundled content.json */\n`);
fs.writeFileSync(path.join(WWW, 'app-config.js'), cfg, 'utf8');

// …and wired into the page, which also loses the browser install button
let html = fs.readFileSync(path.join(WWW, 'index.html'), 'utf8');
html = html.replace(/\n\s*<button id="installBtn"[\s\S]*?<\/button>/, '');
html = html.replace('<!-- APP_CONFIG_SLOT (build-mobile.js inserts the app settings here) -->',
                    '<script src="/app-config.js"></script>');
if (!html.includes('app-config.js')) {
  throw new Error('Could not find the APP_CONFIG_SLOT marker in public/index.html');
}
fs.writeFileSync(path.join(WWW, 'index.html'), html, 'utf8');

/* --- report --- */
function walk(dir, base = dir) {
  let out = [];
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) out = out.concat(walk(p, base));
    else out.push(path.relative(base, p));
  }
  return out;
}
const files = walk(WWW);
const bytes = files.reduce((n, f) => n + fs.statSync(path.join(WWW, f)).size, 0);

console.log('Built mobile/www — ' + files.length + ' files, ' + Math.round(bytes / 1024) + ' KB');
console.log('Content source: ' + (API_BASE ? API_BASE + '/api/content  (falls back to the bundled copy)'
                                           : 'bundled content.json only'));
console.log('\nNext:');
console.log('  cd mobile');
console.log('  npm install');
console.log('  npx cap add android      # and/or:  npx cap add ios   (needs a Mac + Xcode)');
console.log('  npx cap sync');
console.log('  npx cap open android');
